### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by Cumquat** [includable/react-native-map-link#2]
Love the code this is great and works fantastic for all the supplies i use apart from Google maps. When it tries to use google maps on an Iphone it just opens google maps but doesn't go to the supplied lat and long it seems to be looking more for what is passed in the title prop rather than using the supplied coordinates. My code is the same as example code except i'm passing different coorordinates which work on Apple Maps, Waze etc. Any ideas any one else with this problem?
"react-native": "^0.49.3",  "react": "^16.0.0-beta.5", "react-native-map-link": "^1.0.5",

**Comment by tschoffelen** [comment]
True, it currently passes the geolocation provided as the center point of the map (`ll` parameter), and the title as the search query (`q` parameter), since the URL scheme for Google Maps doesn't seem to allow to pass a different search query than what is displayed.

So passing the coordinates as the search query will work more as expected, but will also show the coordinates as the location title, in my opinion (at least for the way I implemented this in the app I initially wrote it for) leading to a worse user experience.

Try the difference:

- comgooglemaps://?api=1&ll=52.3752182,4.8817878&q=Anne+Frank+House
- comgooglemaps://?api=1&q=52.3752182,4.8817878

The first is how it is currently implemented

**Comment by Cumquat** [comment]
Thanks for your response, yea that works perfect, just annoyed at myself for not thinking of that myself.
Cheers

Mick

**Comment by tschoffelen** [comment]
No worries, it’s quite an annoying and slightly abnormal way in which the Google Maps URL scheme works. I hope my explanation cleared things up.
