### ISSUE TITLE
Missing apps: Doesn't detect all installed apps

### ISSUE THREAD

**Issue by ansmlc** [includable/react-native-map-link#279]
I'm testing this library and I've noticed it doesn't detect all available apps. I've followed the [managed expo workflow guide](https://github.com/includable/react-native-map-link/blob/master/docs/expo.md).

On my phone (iOS) I have following apps installed:

- Mapy.cz
- Navi
- MAPS.ME
- Moovit
- Google Maps
- Maps (Apple)
- Waze

However, the lib **only detects Apple Maps** and **Waze.** (and Google Maps if `alwaysIncludeGoogle` is `true`).

This is my code:

```
import React, { useState, useEffect } from 'react';
import { Pressable, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { getApps } from 'react-native-map-link';
import { GetAppsResponse } from 'react-native-map-link/lib/type';
import Colors from '@/src/constants/Colors';

type GetAppResult = {
  id: string;
  name: string;
  icon: NodeRequire;
  open: () => Promise<void>;
};

type DemoProps = {
  lat: number;
  long: number;
  title: string;
};


export const Demo: React.FC<DemoProps> = ({ lat, long, title }) => {
  const [availableApps, setAvailableApps] = useState<GetAppsResponse[]>([]);
  useEffect(() => {
    (async () => {
      const result = await getApps({
        latitude: lat,
        longitude: long,
        title: title,
        googleForceLatLon: true, // optionally force GoogleMaps to use the latlon for the query instead of the title
        alwaysIncludeGoogle: true, // optional, true will always add Google Maps to iOS and open in Safari, even if app is not installed (default: false)
      });
      setAvailableApps(result);
    })();
  }, []);

  return (
    <View style={{ flexDirection: 'column' }}>
      {availableApps.map(({ icon, name, id, open }) => (
        <Pressable
          key={id}
          onPress={open}
          style={{
            borderWidth: 1,
            borderColor: Colors.gray,
            borderRadius: 12,
            padding: 8,
            width: 120,
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignContent: 'center',
            alignItems: 'center',
            marginHorizontal: 4,
          }}
        >
          <Image source={icon} style={{ width: 25, height: 25 }} />
          <Text>{name}</Text>
        </Pressable>
      ))}
    </View>
  );
};
```

Screenshot
<img width="145" alt="image" src="https://github.com/includable/react-native-map-link/assets/50321640/800adadf-ade8-4022-863a-52ac22d94a29">

**Comment by tschoffelen** [comment]
Hi there - just to confirm, could you double check you've recompiled the app after adding the app.json config?

**Comment by tschoffelen** [comment]
Oh I see! The Expo Go app has it's own whitelist of applications - which does include Waze, but none of the others:

https://github.com/expo/expo/blob/main/apps/expo-go/ios/Exponent/Supporting/Info.plist#L75-L82

**Comment by tschoffelen** [comment]
> So just to confirm, to really test the lib I'll need Apple's Dev account and install the app directly on the device, right?

Yes, correct! Unfortunately that's the only way I'm aware of for Apple devices.

**Comment by henriquemafra** [comment]
@ansmlc 

Today I spent the day trying to get MAPS.ME to work around here. I tried adding a native module, tried many things, and got to something I’d say is 95% functional, but not perfect.

**1 -** I changed the constant from mapsme to ge0://
`'maps-me': 'ge0://',
`
**2 -** I created a file called encoder.js and added a function to encode the data into a usable URL.
`
// Constants defined in the header file
const kMaxPointBytes = 10;
const kMaxCoordBits = kMaxPointBytes * 3;

/**
 * Generates a Maps.me short URL for a location
 * @param {number} lat - Latitude in decimal degrees (-90 to 90)
 * @param {number} lon - Longitude in decimal degrees (-180 to 180)
 * @param {number} zoom - Zoom level (typically 4 to 20)
 * @param {string} name - Optional location name
 * @returns {string} URL in the format "ge0://ZCoordba64/Name"
 */
function generateShortShowMapUrl(lat, lon, zoom, name = "") {
  let urlPrefix = "ge0://ZCoordba64";
  
  // Calculate zoom index (0-63)
  const zoomI = (zoom <= 4 ? 0 : (zoom >= 19.75 ? 63 : Math.floor((zoom - 4) * 4)));
  
  // Replace the 7th character (index 6) with the base64 encoded zoom
  urlPrefix = urlPrefix.substring(0, 6) + base64Char(zoomI) + urlPrefix.substring(7);
  
  // Create a character array for the coordinates
  let coordChars = new Array(9).fill('0');
  
  // Fill the coordinate characters starting at position 7
  latLonToString(lat, lon, coordChars, 9);
  
  // Replace characters in the URL prefix with the coordinate encoding
  for (let i = 0; i < 9; i++) {
    urlPrefix = urlPrefix.substring(0, 7 + i) + coordChars[i] + urlPrefix.substring(8 + i);
  }
  
  // Build the final result
  let result = urlPrefix;
  if (name && name.length > 0) {
    result += "/";
    result += transformName(name);
  }
  
  return result;
}

/**
 * Converts an integer (0-63) to a base64 character
 * @param {number} x - Integer between 0 and 63
 * @returns {string} Single base64 character
 */
function base64Char(x) {
  if (x < 0 || x >= 64) {
    throw new Error("Base64 value must be between 0 and 63");
  }
  return "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(x);
}

/**
 * Maps latitude from [-90, 90] to [0, maxValue]
 * @param {number} lat - Latitude in decimal degrees
 * @param {number} maxValue - Maximum integer value
 * @returns {number} Integer representation of latitude
 */
function latToInt(lat, maxValue) {
  const x = (lat + 90.0) / 180.0 * maxValue;
  return x < 0 ? 0 : (x > maxValue ? maxValue : Math.round(x));
}

/**
 * Normalizes longitude to range [-180, 180)
 * @param {number} lon - Longitude in decimal degrees
 * @returns {number} Normalized longitude
 */
function lonIn180180(lon) {
  if (lon >= 0) {
    return ((lon + 180.0) % 360.0) - 180.0;
  }
  // Handle the case of lon = -180
  const l = ((lon - 180.0) % 360.0) + 180.0;
  return l < 180.0 ? l : l - 360.0;
}

/**
 * Maps longitude from [-180, 180) to [0, maxValue]
 * @param {number} lon - Longitude in decimal degrees
 * @param {number} maxValue - Maximum integer value
 * @returns {number} Integer representation of longitude
 */
function lonToInt(lon, maxValue) {
  const x = (lonIn180180(lon) + 180.0) / 360.0 * (maxValue + 1.0) + 0.5;
  return (x <= 0 || x >= maxValue + 1) ? 0 : Math.floor(x);
}

/**
 * Encodes latitude and longitude as a string of base64 characters
 * @param {number} lat - Latitude in decimal degrees
 * @param {number} lon - Longitude in decimal degrees
 * @param {array} s - Array to store the encoded characters
 * @param {number} nBytes - Number of bytes/characters to encode (max 10)
 */
function latLonToString(lat, lon, s, nBytes) {
  if (nBytes > kMaxPointBytes) {
    nBytes = kMaxPointBytes;
  }
  
  const latI = latToInt(lat, (1 << kMaxCoordBits) - 1);
  const lonI = lonToInt(lon, (1 << kMaxCoordBits) - 1);
  
  for (let i = 0, shift = kMaxCoordBits - 3; i < nBytes; ++i, shift -= 3) {
    const latBits = (latI >> shift) & 7;
    const lonBits = (lonI >> shift) & 7;
    
    const nextByte = 
      ((latBits >> 2) & 1) << 5 |
      ((lonBits >> 2) & 1) << 4 |
      ((latBits >> 1) & 1) << 3 |
      ((lonBits >> 1) & 1) << 2 |
      (latBits & 1) << 1 |
      (lonBits & 1);
    
    s[i] = base64Char(nextByte);
  }
}

/**
 * Transforms a string by replacing spaces with underscores and vice versa
 * @param {string} s - Input string
 * @returns {string} Transformed string
 */
function transformName(s) {
  let result = "";
  for (let i = 0; i < s.length; i++) {
    if (s[i] === ' ') {
      result += '_';
    } else if (s[i] === '_') {
      result += ' ';
    } else {
      result += s[i];
    }
  }
  return result;
}

/**
 * URL-encodes a string according to RFC standards
 * @param {string} s - Input string
 * @returns {string} URL-encoded string
 */
function urlEncodeString(s) {
  let result = "";
  const hexChars = "0123456789ABCDEF";
  
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    
    if (c <= 0x1F || c === 0x7F || 
        " <>\"#%!*'();:@&=+$,/?[]{}|^`".indexOf(s[i]) !== -1) {
      result += '%';
      result += hexChars[(c >> 4) & 15];
      result += hexChars[c & 15];
    } else {
      result += s[i];
    }
  }
  
  return result;
}

// Export the functions
exports.generateShortShowMapUrl = generateShortShowMapUrl;
exports.base64Char = base64Char;
exports.latToInt = latToInt;
exports.lonIn180180 = lonIn180180;
exports.lonToInt = lonToInt;
exports.latLonToString = latLonToString;

`

**3 -** This is where things got tricky. I managed to generate the URL, but there was a problem. When opening the URL using Linking, the Maps.me app would only add a non-interactive marker at the map location. However, I realized that if I used the same URL through the browser, Maps.me worked perfectly — opening the address and offering the option to start a route. After trying many ways to solve this, I had to get creative: I built a very simple HTML redirect app and deployed it to Vercel. This way, it redirects to the browser, and the browser opens Maps.me correctly — a fast and almost unnoticeable process. Then I updated the case in utils.js as follows:

`
case 'maps-me':
      url = `https://your-redirect-simple-app.vercel.app/?redirect=${generateShortShowMapUrl(lat, lng, zoom, title)}`;
break;

`

**4 -** And now comes the reason why it's only 95% functional: when opening the route in Maps.me, some addresses appear as 'unknown location', and I still haven’t figured out why. But I’ll try to solve that later, since it doesn’t affect the proper functionality in my case — considering that the geolocation and the generated route are both correct.

**5 -** Finally, I created a patch using patch-package.

I hope this helps in some way. Good luck!
