### ISSUE TITLE
Remember last app selection

### ISSUE THREAD

**Issue by gbahamondezc** [includable/react-native-map-link#31]
Hi, what do you think about to have an option to  remember last app selection?

I mean when the user selects a navigation app, give them another option to remember the last selected app for future interactions.

Makes sense or maybe is something which not correspond to the scope of this library?

**Comment by tschoffelen** [comment]
Is this something you need for your app, or just an idea for this library?

I understand the thought behind it and see its value, but I'm afraid adding features like this might cause us to end up with a bulky and overly complex library, instead of the super simple thing it is today. 

So my initial reaction would be that although it might prove helpful in some situations, this is not something that is within the scope of the library.

(Also, UX: the fact that Android always does this – the "do you want to use this app 'just once' / 'always'" option – always stops me for a second from what I'm doing, to make me think about if there is ever a situation in which I would want that particular file/link type to be opened in a different app, so I don't think this actually helps with regards to usability.)

**Comment by gbahamondezc** [comment]
@tschoffelen Yes, is something specifically to my use case, but i was not sure if it maybe can be useful to others, that's exactly why i asked  here 👍

I agree with you in some points, but i was not 100% sure, that's why i asked, now seems clear to me.

Thanks
