### ISSUE TITLE
Android build fail

### ISSUE THREAD

**Issue by n7229** [includable/react-native-map-link#35]
android/app/build/intermediates/res/merged/release/drawable-xhdpi/node_modules_reactnativemaplink_as
sets_images_yandex.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.

**Comment by tschoffelen** [comment]
This does seem to be related to the React Native build process, not to this library, since it includes images in the normal way.

Try removing your Android build folders and running a clean build, I think that might help.

**Comment by gbahamondezc** [comment]
Same issue here.

Android SDK 26.
Gradle 4.4

I'm not sure if this problem is related with the library, so i will trying to understand what it's going on, to give more details.

**Comment by tschoffelen** [comment]
`android.enableAapt2=false` seems to indeed be the solution whenever you face this problem. I’m closing this issue however, since it doesn’t seem to be specific to this library, but a bug in React Native’s build system, since I’ve experienced this same thing before with other libraries, but am
also able create a RN project with just this library, and then I’m not experiencing this problem.
