### ISSUE TITLE
Expo: isAppInstalled does not detect Google Maps app on iOS 

### ISSUE THREAD

**Issue by grzjos** [includable/react-native-map-link#39]
When I added yet another prefix for the Google Maps (just an example)  Linking.canOpenURL returns true. Otherwise, it is false. Is there any option to provide the list prefixes as a parameter to Popup? Or how otherwise should I solve it?
I work on an Expo based React Native app.
export const prefixes = {
...
  'google-maps': isIOS ? 'comgooglemaps://' : 'https://maps.google.com/',  
  **'google-maps':  'https://maps.google.com/',**
 ...
}

Btw. great job on that library!

**Comment by tschoffelen** [comment]
That specific prefix is chosen because the `maps.google.com` one doesn't always work on iOS.

Besides, this library isn't going to be of much use to you in an Expo app, unless you eject, because you have to follow the install step in the README of adding some items to `Info.plist` to be able to open any of the apps that this library supports.
