### ISSUE TITLE
Google maps never show the location, just loading

### ISSUE THREAD

**Issue by mpargar** [includable/react-native-map-link#52]
Sorry for my english in advance.

I'm testing with the example code and works perfectly in all platforms (i test just in my android device) excepts in G-Maps. The map never shows the location pointer and just put the loading icon in the search bar.

![image](https://user-images.githubusercontent.com/32663960/48997945-ecd4b800-f10e-11e8-87a5-1be1abc0263b.png)

I'm using a Moto G5 plus - Android 8.1.0. react-native@0.57.4

**Comment by tschoffelen** [comment]
Thanks for using the library.

I don't have access to an Android device to test right now, but we recently made some changes in the Google Maps logic, and I think that might be the culprit.

Could you try installing version 2.1.1 of the library (so not `^2.1.1` but just `2.1.1` in your `package.json` file, so that NPM/Yarn uses that exact version) and see if that helps?

Thanks in advance!

**Comment by tugcanolgun** [comment]
I have the same problem and I tried to install 2.1.1 but it didn't help.

**Comment by RobertoE91** [comment]
same problem on  `"react-native-map-link": "^2.1.3"` . Going back to `"react-native-map-link": "2.1.1"`  fix the problem. Thank you.

**Comment by pmjlopez** [comment]
Going back to 2.1.1 worked but when clicking on the Google Maps option with Citymapper installed another popup opens above it.

![image](https://user-images.githubusercontent.com/3843459/49516720-396d7f80-f8d5-11e8-8fe7-fdef2e809405.png)

**Comment by tschoffelen** [comment]
I have just restored the behaviour from version 2.1.1 in the newly released NPM version 2.1.4.

This does re-introduce the problem that we attempted to resolve with #49 (the duplicate dialogs caused by CityMapper), but it is better than Google Maps not functioning at all.

If someone has a better solution for #49, please let me know!
